esphome:
  name: can-bus-battery
  friendly_name: CAN bus battery

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key:

ota:
  - platform: esphome
    password:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Can-Bus-Battery Fallback Hotspot"
    password:

captive_portal:

# Set pins required for LilyGo T-CAN485 board
output:
  - platform: gpio
    id: ENABLE_PIN # Enable the chip
    pin:
      number: GPIO19
      inverted: true
  - platform: gpio
    id: SE_PIN # Enable autodirection
    pin:
      number: GPIO17
      inverted: true
  - platform: gpio
    id: ENABLE_5V_PIN # Enable 5V pin for RS485 chip
    pin:
      number: GPIO16
      inverted: true

canbus:
  - platform: esp32_can
    can_id: 0x123
    mode: LISTENONLY
    tx_pin: GPIO27
    rx_pin: GPIO26
    bit_rate: 500kbps
    on_frame:
      - can_id: 0x355
        then:
          - sensor.template.publish:
              id: PylonSOC
              state: !lambda |-
                return x[0];
      - can_id: 0x356
        then:
          - sensor.template.publish:
              id: PylonCurrent
              state: !lambda |-
                int16_t current = ((x[3]<<8) + (x[2]));
                return ((float)current)/10.0f;
          - sensor.template.publish:
              id: PylonVoltage
              state: !lambda |-
                uint16_t voltage = ((x[1]<<8) + (x[0]));
                return ((float)voltage)/100.0f;
          - sensor.template.publish:
              id: PylonWattage
              state: !lambda |-
                float voltage = ((x[1]<<8) + (x[0]))/10.0f;
                int16_t tempcurrent = ((x[3]<<8) + (x[2]));
                float current = ((float)tempcurrent)/100.0f;
                float watts = (int16_t)voltage * current;
                return (watts);
          - sensor.template.publish:
              id: PylonAvgTemperature
              state: !lambda |-
                int16_t temp = ((x[5]<<8) + (x[4]));
                return ((float)temp)/10.0f;
          

sensor:
  - platform: template
    id: PylonSOC
    device_class: battery
    name: "Battery SOC"
    unit_of_measurement: "%"
    accuracy_decimals: 0
  - platform: template
    id: PylonCurrent
    device_class: current
    name: "Battery current"
    unit_of_measurement: "A"
    accuracy_decimals: 1
  - platform: template
    id: PylonVoltage
    device_class: voltage
    name: "Battery voltage"
    unit_of_measurement: "V"
    accuracy_decimals: 2
  - platform: template
    id: PylonWattage
    device_class: power
    name: "Battery wattage"
    unit_of_measurement: "W"
    accuracy_decimals: 0
  - platform: template
    id: PylonAvgTemperature
    device_class: temperature
    name: "Battery average temperature"
    unit_of_measurement: "℃"
    accuracy_decimals: 1